### ISSUE TITLE
Duplicate storage root created

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/javaDataPipeline#1]
@B0SKAMP - I'm playing with the Java implementation - using the instructions I wrote in the README at https://github.com/FAIRDataPipeline/javaSimpleModel - and it's all working well, but I've spotted a small problem with the storage roots.

After running it, the Java API has added a new storage root - http://localhost:8000/api/storage_root/?format=json returns:

```json
{"count":3,
"next":null,
"previous":null,
"results":[
  {
    "url":"http://localhost:8000/api/storage_root/3/?format=json",
    "last_updated":"2021-09-22T18:12:58.585425Z",
    "root":"https://github.com/",
    "local":false,
    "updated_by":"http://localhost:8000/api/users/1/?format=json",
    "locations":["http://localhost:8000/api/storage_location/4/?format=json"]
  },
  {
    "url":"http://localhost:8000/api/storage_root/2/?format=json",
    "last_updated":"2021-09-22T18:12:58.461483Z",
    "root":"/Users/richardr/.fair/data/",
    "local":false,
    "updated_by":"http://localhost:8000/api/users/1/?format=json",
    "locations":["http://localhost:8000/api/storage_location/2/?format=json","http://localhost:8000/api/storage_location/3/?format=json","http://localhost:8000/api/storage_location/5/?format=json"]
  },
  {
    "url":"http://localhost:8000/api/storage_root/1/?format=json",
    "last_updated":"2021-09-22T18:12:50.867876Z",
    "root":"file:///Users/richardr/.fair/data/",
    "local":true,
    "updated_by":"http://localhost:8000/api/users/1/?format=json",
    "locations":["http://localhost:8000/api/storage_location/1/?format=json"]
  }
]
}
```

Storage root 2 doesn't prepend `file://`, which I think it probably should in order to be a valid link for the browser, but it would in any event be better if it reused the existing storage root (1) created by `fair`, because duplicating them like this is confusing when they represent the same "real" root.

**Comment by richardreeve** [comment]
Note that this inconsistency is almost certainly caused by `fair` because the working config provides the `write_data_store` as just `/Users/richardr/.fair/data/` for convenience, but I think when uploading this to the registry it would be better to add `file://` anyway (and then it would be identified as a duplicate hopefully?). However, `write_data_store` could instead be passed as `file:///Users/richardr/.fair/data/` if that seems like a better idea?

**Comment by B0SKAMP** [comment]
Well spotted! I'll fix that today. Sent from Android deviceOn 23 Sep 2021 00:27, Richard Reeve ***@***.***> wrote:
Note that this inconsistency is almost certainly caused by fair because the working config provides the write_data_store as just /Users/richardr/.fair/data/ for convenience, but I think when uploading this to the registry it would be better to add file:// anyway (and then it would be identified as a duplicate hopefully?). However, write_data_store could instead be passed as file:///Users/richardr/.fair/data/ if that seems like a better idea?
